### PR TITLE
add package.json

### PR DESCRIPTION
**Pull request by mchelen**

### CODE REVIEW

**Comment by carlvlewis** [comment]
Thanks, just reading through docs on the dependencies for this (command line didn't list them), but will know for next time when I compile a condensed version for less academic contexts.

**Comment by mchelen** [comment]
Yeah I just going by `index.js` it looked like `handlebars` was the only requirement.

**Comment by carlvlewis** [comment]
Just published to NPM, @mchelen, and it looks like I'm going to have to merge my CSS stylesheets into a single 'style.css' in the project root (which is doable but not optimal given that I have separate print and screen stylesheets).

**Comment by carlvlewis** [comment]
See error list: http://themes.jsonresume.org/cvstrap

**Pull request merged**
